create schema EST_CASO_V1;

use EST_CASO_V1;

create table if not exists CLIENTES(
ID_CLIENT INT PRIMARY KEY,
CPF_CLIENT VARCHAR(14) NOT NULL,
NOME_CLIENT VARCHAR(50) NOT NULL,
DATA_NASC_CLIENT DATE NOT NULL,
EMAIL_CLIENT VARCHAR(50) NOT NULL,
TEL_CLIENT VARCHAR(20) NOT NULL,
RUA_CLIENT VARCHAR(100) NOT NULL,
NUM_RES_CLIENT INT,
CEP_CLIENT VARCHAR(10) NOT NULL,
BAIRRO_CLIENT VARCHAR(50) NOT NULL,
CIDADE_CLIENT VARCHAR(50) NOT NULL,
UF_CLIENT VARCHAR(2) NOT NULL,
STATUS_FID_CLIENT ENUM('ATIVO','INATIVO')
);

ALTER TABLE CLIENTES MODIFY column BAIRRO_CLIENT VARCHAR(100);
ALTER TABLE CLIENTES ADD column PAIS_CLIENT VARCHAR(50) NOT NULL;

create table if not exists PRODUTOS(
ID_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR(50) NOT NULL,
QTD_EST_PROD INT NOT NULL,
VALOR_UNIT_PROD DECIMAL(4,2) NOT NULL,
ESP_TEC_PROD TEXT NOT NULL
);

ALTER TABLE PRODUTOS ADD column DESC_PROD TEXT NOT NULL;

create table if not exists FORNECEDORES(
ID_FORN INT PRIMARY KEY,
RAZ_SOC_FORN VARCHAR(50) NOT NULL,
CNPJ_FORN VARCHAR(20) NOT NULL,
EMAIL_FORN VARCHAR(50) NOT NULL,
TEL_FORN VARCHAR(20) NOT NULL,
RUA_FORN VARCHAR(100) NOT NULL,
NUM_LOC_FORN INT,
CEP_FORN VARCHAR(10) NOT NULL,
BAIRRO_FORN VARCHAR(50) NOT NULL,
CIDADE_FORN VARCHAR(50) NOT NULL,
UF_FORN VARCHAR(2),
PAIS_FORN VARCHAR(50) NOT NULL
);

ALTER TABLE FORNECEDORES modify column BAIRRO_FORN VARCHAR(100);

create table if not exists VENDAS(
ID_VENDA INT PRIMARY KEY,
VALOR_VENDA DECIMAL(10,2) NOT NULL,
DATA_VENDA DATE NOT NULL,
CLIENT_VENDA INT NOT NULL,
CONSTRAINT FK_VENDA_CLIENTES FOREIGN KEY(CLIENT_VENDA) REFERENCES CLIENTES(ID_CLIENT)
);

ALTER TABLE VENDAS DROP COLUMN DATA_VENDA; 

create table if not exists PAGAMENTOS(
ID_PAG INT PRIMARY KEY,
VALOR_PAG DECIMAL(10,2) NOT NULL,
DATA_PAG DATE NOT NULL,
DESCONTO_PAG DECIMAL(10,2) NOT NULL,
PARCELAS_PAG INT NOT NULL,
ID_FORM_PAG INT NOT NULL,
STATUS_PAG ENUM('PAGO','PENDENTE'),
VENDA_PAG INT NOT NULL,
CONSTRAINT FK_PAG_VENDAS FOREIGN KEY (VENDA_PAG) REFERENCES VENDAS(ID_VENDA)
);

ALTER TABLE PAGAMENTOS MODIFY DESCONTO_PAG DECIMAL(3,2);

create table if not exists PRODUTOS_FORNECEDORES(
PRFR_PROD INT,
PRFR_FORN INT,
PRIMARY KEY (PRFR_PROD, PRFR_FORN),
CONSTRAINT FK_PRFR_PRODUTOS FOREIGN KEY (PRFR_PROD) REFERENCES PRODUTOS(ID_PROD),
CONSTRAINT FK_PRFR_FORNECEDORES FOREIGN KEY (PRFR_FORN) REFERENCES FORNECEDORES(ID_FORN)
);

ALTER TABLE PRODUTOS_FORNECEDORES ADD column PRFR_DESC TEXT;

create table if not exists PRODUTOS_VENDAS (
PRVN_PROD INT,
PRVN_VEND INT,
PRIMARY KEY (PRVN_PROD, PRVN_VEND),
CONSTRAINT FK_PRVN_PRODUTOS FOREIGN KEY (PRVN_PROD) REFERENCES PRODUTOS(ID_PROD),
CONSTRAINT FK_PRVN_VENDAS FOREIGN KEY (PRVN_VEND) REFERENCES VENDAS(ID_VENDA)
);

ALTER TABLE PRODUTOS_FORNECEDORES ADD column PRVN_DESC TEXT;

DROP SCHEMA EST_CASO_V1;
