#CRIAR BANCO DE DADOS 

create schema ec3;

use ec3;

#CRIAR TABELA CLIENTES E DAR COMANDOS DE ALTER NA MESMA

create table if not exists CLIENTES(
COD_CLIENT INT PRIMARY KEY,
CNPJ_CLIENT VARCHAR(20) NOT NULL,
RAZ_SOC_CLIENT VARCHAR(50) NOT NULL,
RAM_ATV_CLIENT VARCHAR(100) NOT NULL,
DATA_CAD_CLIENT DATE NOT NULL
);

ALTER TABLE CLIENTES ADD COLUMN DESC_CLIENT TEXT NOT NULL;
ALTER TABLE CLIENTES MODIFY COLUMN DESC_CLIENT VARCHAR(100);
ALTER TABLE CLIENTES CHANGE COLUMN DESC_CLIENT DESCR_CLIENT VARCHAR(100);
ALTER TABLE CLIENTES DROP COLUMN DESCR_CLIENT;

#CRIAR TABELA FORNECEDORES E DAR COMANDOS DE ALTER NA MESMA

create table if not exists FORNECEDORES(
COD_FORN INT PRIMARY KEY,
CNPJ_FORN VARCHAR(20) NOT NULL,
RAZ_SOC_FORN VARCHAR(50) NOT NULL
);

ALTER TABLE FORNECEDORES ADD COLUMN DESC_FORN TEXT NOT NULL;
ALTER TABLE FORNECEDORES MODIFY COLUMN DESC_FORN VARCHAR(100);
ALTER TABLE FORNECEDORES CHANGE COLUMN DESC_FORN DESCR_FORN VARCHAR(100);
ALTER TABLE FORNECEDORES DROP COLUMN DESCR_FORN;

#CRIAR TABELA TIPOS_ENDERECOS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists TIPOS_ENDERECOS(
COD_TIPO_END INT PRIMARY KEY,
NOME_TIPO_END VARCHAR(20) NOT NULL
);

ALTER TABLE TIPOS_ENDERECOS ADD COLUMN DESC_TIPO_END TEXT NOT NULL;
ALTER TABLE TIPOS_ENDERECOS MODIFY COLUMN DESC_TIPO_END VARCHAR(100);
ALTER TABLE TIPOS_ENDERECOS CHANGE COLUMN DESC_TIPO_END DESCR_TIPO_END VARCHAR(100);
ALTER TABLE TIPOS_ENDERECOS DROP COLUMN DESCR_TIPO_END;

#CRIAR TABELA QUALIFICACOES E DAR COMANDOS DE ALTER NA MESMA

create table if not exists QUALIFICACOES(
COD_QLF INT PRIMARY KEY,
NOME_QLF VARCHAR(20) NOT NULL
);

ALTER TABLE QUALIFICACOES ADD COLUMN DESC_QLF TEXT NOT NULL;
ALTER TABLE QUALIFICACOES MODIFY COLUMN DESC_QLF VARCHAR(100);
ALTER TABLE QUALIFICACOES CHANGE COLUMN DESC_QLF DESCR_QLF VARCHAR(100);
ALTER TABLE QUALIFICACOES DROP COLUMN DESCR_QLF;

#CRIAR TABELA PESSOAS_CONTATO E DAR COMANDOS DE ALTER NA MESMA

create table if not exists PESSOAS_CONTATO(
COD_PES_CONT INT PRIMARY KEY,
NOME_PES_CONT VARCHAR(50) NOT NULL,
CPF_PES_CONT VARCHAR(14) NOT NULL
);

ALTER TABLE PESSOAS_CONTATO ADD COLUMN DESC_PES_CONT TEXT NOT NULL;
ALTER TABLE PESSOAS_CONTATO MODIFY COLUMN DESC_PES_CONT VARCHAR(100);
ALTER TABLE PESSOAS_CONTATO CHANGE COLUMN DESC_PES_CONT DESCR_PES_CONT VARCHAR(100);
ALTER TABLE PESSOAS_CONTATO DROP COLUMN DESCR_PES_CONT;

#CRIAR TABELA CARGOS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists CARGOS(
COD_CARGO INT PRIMARY KEY,
NOME_CARGO VARCHAR(20) NOT NULL,
DESC_FUNC_CARGO TEXT NOT NULL
);

ALTER TABLE CARGOS ADD COLUMN DESC_CARGO TEXT NOT NULL;
ALTER TABLE CARGOS MODIFY COLUMN DESC_CARGO VARCHAR(100);
ALTER TABLE CARGOS CHANGE COLUMN DESC_CARGO DESCR_CARGO VARCHAR(100);
ALTER TABLE CARGOS DROP COLUMN DESCR_CARGO;

#CRIAR TABELA PRODUTOS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists PRODUTOS(
COD_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR(30) NOT NULL,
COR_PROD VARCHAR(15) NOT NULL,
DIM_PROD TEXT NOT NULL,
PESO_PROD DECIMAL(10,3) NOT NULL,
PRECO_PROD DECIMAL(10,2) NOT NULL,
TEMP_FAB_PROD VARCHAR(10) NOT NULL,
DESENHO_PROD BLOB NOT NULL,
HRS_MOBRA_PROD VARCHAR(10) NOT NULL
);

ALTER TABLE PRODUTOS ADD COLUMN DESC_PROD TEXT NOT NULL;
ALTER TABLE PRODUTOS MODIFY COLUMN DESC_PROD VARCHAR(100);
ALTER TABLE PRODUTOS CHANGE COLUMN DESC_PROD DESCR_PROD VARCHAR(100);
ALTER TABLE PRODUTOS DROP COLUMN DESCR_PROD;

#CRIAR TABELA TIPOS_COMPONENTES E DAR COMANDOS DE ALTER NA MESMA

create table if not exists TIPOS_COMPONENTES(
COD_TIP_COMP INT PRIMARY KEY,
NOME_TIP_COMP VARCHAR(20) NOT NULL
);

ALTER TABLE TIPOS_COMPONENTES ADD COLUMN DESC_TIP_COMP TEXT NOT NULL;
ALTER TABLE TIPOS_COMPONENTES MODIFY COLUMN DESC_TIP_COMP VARCHAR(100);
ALTER TABLE TIPOS_COMPONENTES CHANGE COLUMN DESC_TIP_COMP DESCR_TIP_COMP VARCHAR(100);
ALTER TABLE TIPOS_COMPONENTES DROP COLUMN DESCR_TIP_COMP;

#CRIAR TABELA MAQUINAS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists MAQUINAS(
COD_MAQ INT PRIMARY KEY,
TEMP_VID_MAQ VARCHAR(20) NOT NULL,
DATA_CMP_MAQ DATE NOT NULL,
DATA_FIM_GART_MAQ DATE NOT NULL
);

ALTER TABLE MAQUINAS ADD COLUMN DESC_MAQ TEXT NOT NULL;
ALTER TABLE MAQUINAS MODIFY COLUMN DESC_MAQ VARCHAR(100);
ALTER TABLE MAQUINAS CHANGE COLUMN DESC_MAQ DESCR_MAQ VARCHAR(100);
ALTER TABLE MAQUINAS DROP COLUMN DESCR_MAQ;

#CRIAR TABELA EMPREGADOS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists EMPREGADOS(
MATR_EMPREG INT PRIMARY KEY,
NOME_EMPREG VARCHAR(100) NOT NULL,
CPF_EMPREG VARCHAR(14) NOT NULL,
SAL_EMPREG DECIMAL(10,2) NOT NULL,
DATA_ADM_EMPREG DATE NOT NULL,
CARGO_EMPREG INT NOT NULL,
CONSTRAINT FK_CARGOS FOREIGN KEY (CARGO_EMPREG) REFERENCES CARGOS(COD_CARGO)
);

ALTER TABLE EMPREGADOS ADD COLUMN DESC_EMPREG TEXT NOT NULL;
ALTER TABLE EMPREGADOS MODIFY COLUMN DESC_EMPREG VARCHAR(100);
ALTER TABLE EMPREGADOS CHANGE COLUMN DESC_EMPREG DESCR_EMPREG VARCHAR(100);
ALTER TABLE EMPREGADOS DROP COLUMN DESCR_EMPREG;

#CRIAR TABELA ENDERECOS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists ENDERECOS(
COD_ENDRC INT PRIMARY KEY,
CEP_ENDRC VARCHAR(10) NOT NULL,
RUA_ENDRC VARCHAR(100) NOT NULL,
NUM_ENDRC INT,
COMP_ENDRC VARCHAR(100) NOT NULL,
LOG_ENDRC VARCHAR(100) NOT NULL,
BAIRRO_ENDRC VARCHAR(100) NOT NULL,
CID_ENDRC VARCHAR(100) NOT NULL,
ESTADO_ENDRC VARCHAR(100) NOT NULL,
TIPO_END_ENDRC INT NOT NULL,
FORN_ENDRC INT NOT NULL,
CLIENT_ENDRC INT NOT NULL,
EMPREG_ENDRC INT NOT NULL,
CONSTRAINT FK_TIPOS_ENDERECOS FOREIGN KEY (TIPO_END_ENDRC) REFERENCES TIPOS_ENDERECOS(COD_TIPO_END),
CONSTRAINT FK_FORNECEDORES FOREIGN KEY (FORN_ENDRC) REFERENCES FORNECEDORES(COD_FORN),
CONSTRAINT FK_CLIENTES FOREIGN KEY (CLIENT_ENDRC) REFERENCES CLIENTES(COD_CLIENT),
CONSTRAINT FK_EMPREGADOS FOREIGN KEY (EMPREG_ENDRC) REFERENCES EMPREGADOS(MATR_EMPREG)
);

ALTER TABLE ENDERECOS ADD COLUMN DESC_ENDRC TEXT NOT NULL;
ALTER TABLE ENDERECOS MODIFY COLUMN DESC_ENDRC VARCHAR(100);
ALTER TABLE ENDERECOS CHANGE COLUMN DESC_ENDRC DESCR_ENDRC VARCHAR(100);
ALTER TABLE ENDERECOS DROP COLUMN DESCR_ENDRC;

#CRIAR TABELA TELEFONES E DAR COMANDOS DE ALTER NA MESMA

create table if not exists TELEFONES(
DDD_TEL VARCHAR(3),
NUM_TEL VARCHAR(15),
PRIMARY KEY (DDD_TEL, NUM_TEL),
FORN_TEL INT NOT NULL,
CLIENT_TEL INT NOT NULL,
EMPREG_TEL INT NOT NULL,
PES_CONT_TEL INT NOT NULL,
CONSTRAINT FK_FORNECEDORES1 FOREIGN KEY (FORN_TEL) REFERENCES FORNECEDORES(COD_FORN),
CONSTRAINT FK_CLIENTES1 FOREIGN KEY (CLIENT_TEL) REFERENCES CLIENTES(COD_CLIENT),
CONSTRAINT FK_EMPREGADOS1 FOREIGN KEY (EMPREG_TEL) REFERENCES EMPREGADOS(MATR_EMPREG),
CONSTRAINT FK_PESSOAS_CONTATO FOREIGN KEY (PES_CONT_TEL) REFERENCES PESSOAS_CONTATO(COD_PES_CONT)
);

ALTER TABLE TELEFONES ADD COLUMN DESC_TEL TEXT NOT NULL;
ALTER TABLE TELEFONES MODIFY COLUMN DESC_TEL VARCHAR(100);
ALTER TABLE TELEFONES CHANGE COLUMN DESC_TEL DESCR_TEL VARCHAR(100);
ALTER TABLE TELEFONES DROP COLUMN DESCR_TEL;

#CRIAR TABELA ENCOMENDAS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists ENCOMENDAS(
COD_ENCOM INT PRIMARY KEY,
DATA_INCL_ENCOM DATE NOT NULL,
VALOR_TOTAL_ENCOM DECIMAL(10,2) NOT NULL,
VALOR_DESC_ENCOM DECIMAL(10,2) NOT NULL,
QTD_PARC_ENCOM INT NOT NULL,
ID_FORM_PAG_ENCOM INT NOT NULL,
CLIENT_ENCOM INT NOT NULL,
CONSTRAINT FK_CLIENTES2 FOREIGN KEY (CLIENT_ENCOM) REFERENCES CLIENTES(COD_CLIENT)
);

ALTER TABLE ENCOMENDAS ADD COLUMN DESC_ENCOM TEXT NOT NULL;
ALTER TABLE ENCOMENDAS MODIFY COLUMN DESC_ENCOM VARCHAR(100);
ALTER TABLE ENCOMENDAS CHANGE COLUMN DESC_ENCOM DESCR_ENCOM VARCHAR(100);
ALTER TABLE ENCOMENDAS DROP COLUMN DESCR_ENCOM;

#CRIAR TABELA COMPONENTES E DAR COMANDOS DE ALTER NA MESMA

create table if not exists COMPONENTES(
COD_COMP INT PRIMARY KEY,
NOME_COMP VARCHAR(100) NOT NULL,
QTD_EST_COMP INT NOT NULL,
PRC_UNIT_COMP DECIMAL(10,2) NOT NULL,
UNIDADE_COMP VARCHAR(50) NOT NULL,
TIP_COMP_COMP INT NOT NULL,
CONSTRAINT FK_TIPOS_COMPONENTES FOREIGN KEY (TIP_COMP_COMP) REFERENCES TIPOS_COMPONENTES(COD_TIP_COMP)
);

ALTER TABLE COMPONENTES ADD COLUMN DESC_COMP TEXT NOT NULL;
ALTER TABLE COMPONENTES MODIFY COLUMN DESC_COMP VARCHAR(100);
ALTER TABLE COMPONENTES CHANGE COLUMN DESC_COMP DESCR_COMP VARCHAR(100);
ALTER TABLE COMPONENTES DROP COLUMN DESCR_COMP;

#CRIAR TABELA REGISTROS_MANUTENCAO E DAR COMANDOS DE ALTER NA MESMA

create table if not exists REGISTROS_MANUTENCAO(
COD_RM INT PRIMARY KEY,
DATA_RM DATE NOT NULL,
DESC_RM TEXT NOT NULL,
MAQ_RM INT NOT NULL,
CONSTRAINT FK_MAQUINAS FOREIGN KEY (MAQ_RM) REFERENCES MAQUINAS(COD_MAQ)
);

ALTER TABLE REGISTROS_MANUTENCAO ADD COLUMN DESC_RM TEXT NOT NULL;
ALTER TABLE REGISTROS_MANUTENCAO MODIFY COLUMN DESC_RM VARCHAR(100);
ALTER TABLE REGISTROS_MANUTENCAO CHANGE COLUMN DESC_RM DESCR_RM VARCHAR(100);
ALTER TABLE REGISTROS_MANUTENCAO DROP COLUMN DESCR_RM;

#CRIAR TABELA REGISTROS_ESPECIFICOS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists REGISTROS_ESPECIFICOS(
COD_RE INT PRIMARY KEY,
QTD_NEC_RE INT NOT NULL,
UNID_RE VARCHAR(50) NOT NULL,
TEMP_USO_RE VARCHAR(10) NOT NULL,
HRS_MOBRA_RE VARCHAR(10) NOT NULL,
MAQ_RE INT NOT NULL,
COMP_RE INT NOT NULL,
EMPREG_RE INT NOT NULL,
PROD_RE INT NOT NULL,
CONSTRAINT FK_MAQUINAS2 foreign key (MAQ_RE) REFERENCES MAQUINAS(COD_MAQ),
CONSTRAINT FK_COMPONENTES FOREIGN KEY (COMP_RE) REFERENCES COMPONENTES(COD_COMP),
CONSTRAINT FK_EMPREGADOS3 foreign key (EMPREG_RE) references EMPREGADOS(MATR_EMPREG),
CONSTRAINT FK_PRODUTOS FOREIGN KEY (PROD_RE) REFERENCES PRODUTOS(COD_PROD)
);

ALTER TABLE REGISTROS_ESPECIFICOS ADD COLUMN DESC_RE TEXT NOT NULL;
ALTER TABLE REGISTROS_ESPECIFICOS MODIFY COLUMN DESC_RE VARCHAR(100);
ALTER TABLE REGISTROS_ESPECIFICOS CHANGE COLUMN DESC_RE DESCR_RE VARCHAR(100);
ALTER TABLE REGISTROS_ESPECIFICOS DROP COLUMN DESCR_RE;

#CRIAR TABELA REGISTROS_SUPRIMENTO E DAR COMANDOS DE ALTER NA MESMA

create table if not exists REGISTROS_SUPRIMENTO(
RGSP_PROD INT,
RGSP_COMP INT,
PRIMARY KEY(RGSP_PROD, RGSP_COMP),
RGSP_QTD INT NOT NULL,
RGSP_DATA_NEC DATE NOT NULL,
CONSTRAINT FK_PRODUTOS2 FOREIGN KEY (RGSP_PROD) REFERENCES PRODUTOS(COD_PROD),
CONSTRAINT FK_COMPONENTES2 FOREIGN KEY (RGSP_COMP) REFERENCES COMPONENTES(COD_COMP)
);

ALTER TABLE REGISTROS_SUPRIMENTO ADD COLUMN DESC_RGSP TEXT NOT NULL;
ALTER TABLE REGISTROS_SUPRIMENTO MODIFY COLUMN DESC_RGSP VARCHAR(100);
ALTER TABLE REGISTROS_SUPRIMENTO CHANGE COLUMN DESC_RGSP DESCR_RGSP VARCHAR(100);
ALTER TABLE REGISTROS_SUPRIMENTO DROP COLUMN DESCR_RGSP;

#CRIAR TABELA PRODUTOS_ENCOMENDAS E DAR COMANDOS DE ALTER NA MESMA

create table if not exists PRODUTOS_ENCOMENDAS(
PREN_PROD INT,
PREN_ENCOM INT,
PRIMARY KEY(PREN_PROD, PREN_ENCOM),
CONSTRAINT FK_PRODUTOS3 FOREIGN KEY (PREN_PROD) REFERENCES PRODUTOS(COD_PROD),
CONSTRAINT FK_ENCOMENDAS FOREIGN KEY (PREN_ENCOM) REFERENCES ENCOMENDAS(COD_ENCOM)
);

ALTER TABLE PRODUTOS_ENCOMENDAS ADD COLUMN DESC_PREN TEXT NOT NULL;
ALTER TABLE PRODUTOS_ENCOMENDAS MODIFY COLUMN DESC_PREN VARCHAR(100);
ALTER TABLE PRODUTOS_ENCOMENDAS CHANGE COLUMN DESC_PREN DESCR_PREN VARCHAR(100);
ALTER TABLE PRODUTOS_ENCOMENDAS DROP COLUMN DESCR_PREN;

#CRIAR TABELA EMPREGADOS_QUALIFICACOES E DAR COMANDOS DE ALTER NA MESMA

create table if not exists EMPREGADOS_QUALIFICACOES(
EMQL_EMPREG INT,
EMQL_QLF INT,
PRIMARY KEY(EMQL_EMPREG, EMQL_QLF),
CONSTRAINT FK_EMPREGADOS4 FOREIGN KEY (EMQL_EMPREG) REFERENCES EMPREGADOS(MATR_EMPREG),
CONSTRAINT FK_QUALIFICACOES FOREIGN KEY (EMQL_QLF) REFERENCES QUALIFICACOES(COD_QLF)
);

ALTER TABLE EMPREGADOS_QUALIFICACOES ADD COLUMN DESC_EMQL TEXT NOT NULL;
ALTER TABLE EMPREGADOS_QUALIFICACOES MODIFY COLUMN DESC_EMQL VARCHAR(100);
ALTER TABLE EMPREGADOS_QUALIFICACOES CHANGE COLUMN DESC_EMQL DESCR_EMQL VARCHAR(100);
ALTER TABLE EMPREGADOS_QUALIFICACOES DROP COLUMN DESCR_EMQL;

#CRIAR TABELA COMPONENTES_FORNECEDORES E DAR COMANDOS DE ALTER NA MESMA

create table if not exists COMPONENTES_FORNECEDORES(
CMFR_COMP INT,
CMFR_FORN INT,
PRIMARY KEY(CMFR_COMP, CMFR_FORN),
CONSTRAINT FK_COMPONENTES3 FOREIGN KEY (CMFR_COMP) REFERENCES COMPONENTES(COD_COMP),
CONSTRAINT FK_FORNECEDORES2 FOREIGN KEY (CMFR_FORN) REFERENCES FORNECEDORES(COD_FORN)
);

ALTER TABLE COMPONENTES_FORNECEDORES ADD COLUMN DESC_CMFR TEXT NOT NULL;
ALTER TABLE COMPONENTES_FORNECEDORES MODIFY COLUMN DESC_CMFR VARCHAR(100);
ALTER TABLE COMPONENTES_FORNECEDORES CHANGE COLUMN DESC_CMFR DESCR_CMFR VARCHAR(100);
ALTER TABLE COMPONENTES_FORNECEDORES DROP COLUMN DESCR_CMFR;

#COMANDO DE DROP NO BANCO DE DADOS

DROP SCHEMA ec3; 
