#CRIAR SCHEMA EST_CASO_V

create schema EST_CASO_V1;

use EST_CASO_V1;

#CRIAR TABELA CLIENTES

create table if not exists CLIENTES(
ID_CLIENT INT PRIMARY KEY,
CPF_CLIENT VARCHAR(14) NOT NULL,
NOME_CLIENT VARCHAR(50) NOT NULL,
DATA_NASC_CLIENT DATE NOT NULL,
EMAIL_CLIENT VARCHAR(50) NOT NULL,
TEL_CLIENT VARCHAR(20) NOT NULL,
RUA_CLIENT VARCHAR(100) NOT NULL,
NUM_RES_CLIENT INT,
CEP_CLIENT VARCHAR(10) NOT NULL,
BAIRRO_CLIENT VARCHAR(50) NOT NULL,
CIDADE_CLIENT VARCHAR(50) NOT NULL,
UF_CLIENT VARCHAR(2) NOT NULL,
STATUS_FID_CLIENT ENUM('ATIVO','INATIVO')
);

#DAR COMANDOS DE ALTER NA TABELA CLIENTES

ALTER TABLE CLIENTES ADD column PAIS_CLIENT VARCHAR(50) NOT NULL;
ALTER TABLE CLIENTES ADD COLUMN DESC_CLIENT TEXT NOT NULL;
ALTER TABLE CLIENTES MODIFY COLUMN DESC_CLIENT VARCHAR(100);
ALTER TABLE CLIENTES CHANGE COLUMN DESC_CLIENT DESCR_CLIENT VARCHAR(100);
ALTER TABLE CLIENTES DROP COLUMN DESCR_CLIENT;

#CRIAR TABELA PRODUTOS

create table if not exists PRODUTOS(
ID_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR(50) NOT NULL,
QTD_EST_PROD INT NOT NULL,
VALOR_UNIT_PROD DECIMAL(4,2) NOT NULL,
ESP_TEC_PROD TEXT NOT NULL
);

#DAR COMANDOS DE ALTER NA TABELA PRODUTOS

ALTER TABLE PRODUTOS ADD column DESC_PROD TEXT NOT NULL;
ALTER TABLE PRODUTOS MODIFY COLUMN DESC_PROD VARCHAR(100);
ALTER TABLE PRODUTOS CHANGE COLUMN DESC_PROD DESCR_PROD VARCHAR(100);
ALTER TABLE PRODUTOS DROP COLUMN DESCR_PROD;

#CRIAR TABELA FORNECEDORES

create table if not exists FORNECEDORES(
ID_FORN INT PRIMARY KEY,
RAZ_SOC_FORN VARCHAR(50) NOT NULL,
CNPJ_FORN VARCHAR(20) NOT NULL,
EMAIL_FORN VARCHAR(50) NOT NULL,
TEL_FORN VARCHAR(20) NOT NULL,
RUA_FORN VARCHAR(100) NOT NULL,
NUM_LOC_FORN INT,
CEP_FORN VARCHAR(10) NOT NULL,
BAIRRO_FORN VARCHAR(50) NOT NULL,
CIDADE_FORN VARCHAR(50) NOT NULL,
UF_FORN VARCHAR(2),
PAIS_FORN VARCHAR(50) NOT NULL
);

#DAR COMANDOS DE ALTER NA TABELA FORNECEDORES

ALTER TABLE FORNECEDORES ADD column DESC_FORN TEXT NOT NULL;
ALTER TABLE FORNECEDORES MODIFY COLUMN DESC_FORN VARCHAR(100);
ALTER TABLE FORNECEDORES CHANGE COLUMN DESC_FORN DESCR_FORN VARCHAR(100);
ALTER TABLE FORNECEDORES DROP COLUMN DESCR_FORN;

#CRIAR TABELA VENDAS

create table if not exists VENDAS(
ID_VENDA INT PRIMARY KEY,
VALOR_VENDA DECIMAL(10,2) NOT NULL,
DATA_VENDA DATE NOT NULL,
CLIENT_VENDA INT NOT NULL,
CONSTRAINT FK_VENDA_CLIENTES FOREIGN KEY(CLIENT_VENDA) REFERENCES CLIENTES(ID_CLIENT)
);

#DAR COMANDOS DE ALTER NA TABELA VENDAS

ALTER TABLE VENDAS ADD column DESC_VENDA TEXT NOT NULL;
ALTER TABLE VENDAS MODIFY COLUMN DESC_VENDA VARCHAR(100);
ALTER TABLE VENDAS CHANGE COLUMN DESC_VENDA DESCR_VENDA VARCHAR(100);
ALTER TABLE VENDAS DROP COLUMN DESCR_VENDA; 

#CRIAR TABELA PAGAMENTOS

create table if not exists PAGAMENTOS(
ID_PAG INT PRIMARY KEY,
VALOR_PAG DECIMAL(10,2) NOT NULL,
DATA_PAG DATE NOT NULL,
DESCONTO_PAG DECIMAL(10,2) NOT NULL,
PARCELAS_PAG INT NOT NULL,
ID_FORM_PAG INT NOT NULL,
STATUS_PAG ENUM('PAGO','PENDENTE'),
VENDA_PAG INT NOT NULL,
CONSTRAINT FK_PAG_VENDAS FOREIGN KEY (VENDA_PAG) REFERENCES VENDAS(ID_VENDA)
);

#DAR COMANDOS DE ALTER NA TABELA PAGAMENTOS

ALTER TABLE PAGAMENTOS ADD column DESC_FORN TEXT NOT NULL;
ALTER TABLE PAGAMENTOS MODIFY COLUMN DESC_FORN VARCHAR(100);
ALTER TABLE PAGAMENTOS CHANGE COLUMN DESC_FORN DESCR_FORN VARCHAR(100);
ALTER TABLE PAGAMENTOS DROP COLUMN DESCR_FORN;

#CRIAR TABELA PRODUTOS_FORNECEDORES

create table if not exists PRODUTOS_FORNECEDORES(
PRFR_PROD INT,
PRFR_FORN INT,
PRIMARY KEY (PRFR_PROD, PRFR_FORN),
CONSTRAINT FK_PRFR_PRODUTOS FOREIGN KEY (PRFR_PROD) REFERENCES PRODUTOS(ID_PROD),
CONSTRAINT FK_PRFR_FORNECEDORES FOREIGN KEY (PRFR_FORN) REFERENCES FORNECEDORES(ID_FORN)
);

#DAR COMANDOS DE ALTER NA TABELA PRODUTOS_FORNECEDORES

ALTER TABLE PRODUTOS_FORNECEDORES ADD column PRFR_DESC TEXT;
ALTER TABLE PRODUTOS_FORNECEDORES MODIFY column PRFR_DESC VARCHAR(100);
ALTER TABLE PRODUTOS_FORNECEDORES CHANGE column PRFR_DESC PRFR_DESCR VARCHAR(100);
ALTER TABLE PRODUTOS_FORNECEDORES DROP column PRFR_DESCR;

#CRIAR TABELA PRODUTOS_VENDAS

create table if not exists PRODUTOS_VENDAS (
PRVN_PROD INT,
PRVN_VEND INT,
PRIMARY KEY (PRVN_PROD, PRVN_VEND),
CONSTRAINT FK_PRVN_PRODUTOS FOREIGN KEY (PRVN_PROD) REFERENCES PRODUTOS(ID_PROD),
CONSTRAINT FK_PRVN_VENDAS FOREIGN KEY (PRVN_VEND) REFERENCES VENDAS(ID_VENDA)
);

#DAR COMANDOS DE ALTER NA TABELA PRODUTOS_VENDAS

ALTER TABLE PRODUTOS_VENDAS ADD column PRVN_DESC TEXT;
ALTER TABLE PRODUTOS_VENDAS MODIFY column PRVN_DESC VARCHAR(100);
ALTER TABLE PRODUTOS_VENDAS CHANGE column PRVN_DESC PRVN_DESCR VARCHAR(100);
ALTER TABLE PRODUTOS_VENDAS DROP column PRVN_DESCR;

#CRIAR TABELA AUXILIAR QUE RECEBERÁ UM COMANDO DE DROP

CREATE TABLE IF NOT EXISTS AUX(
AUX_ID INT PRIMARY KEY
)

ALTER TABLE AUX ADD COLUMN AUX_DESC TEXT;
ALTER TABLE AUX COLUMN AUX_DESC VARCHAR(100);
ALTER TABLE AUX CHANGE COLUMN AUX_DESC AUX_DESCR VARCHAR(100);
ALTER TABLE AUX DROP COLUMN AUX_DESCR;
  
DROP TABLE AUX;
