create database EST_CASO_II;

use EST_CASO_II;

create table if not exists PASSAGEIROS(
PASS_CPF VARCHAR(14) PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_DATANASC DATE NOT NULL,
PASS_TEL VARCHAR(20) NOT NULL,
PASS_EMAIL VARCHAR(50) NOT NULL,
PASS_CEP VARCHAR(10) NOT NULL,
PASS_RUA VARCHAR(100) NOT NULL,
PASS_RES_NUM INT,
PASS_BAIRRO VARCHAR(50) NOT NULL,
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_UF VARCHAR(2),
PASS_PAIS VARCHAR(30) NOT NULL
);

ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_NOME VARCHAR(100) NOT NULL;

create table if not exists AERONAVES(
AERON_PREFIX VARCHAR(10) PRIMARY KEY,
AERON_MODEL VARCHAR(20) NOT NULL,
AERON_ANOFABR INT NOT NULL,
AERON_AUTON VARCHAR(10) NOT NULL,
AERON_CAPAC INT NOT NULL,
AERON_FABR VARCHAR(30) NOT NULL
);

ALTER TABLE AERONAVES CHANGE column AERON_ANOFABR AERON_DATAFABR DATE NOT NULL;

create table if not exists AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR(50) NOT NULL,
AEROP_CIDADE VARCHAR(50) NOT NULL,
AEROP_PAIS VARCHAR(30) NOT NULL,
AEROP_LATITUDE DECIMAL(3,2) NOT NULL,
AEROP_LONGITUDE DECIMAL(3,2) NOT NULL
);

ALTER TABLE AEROPORTOS ADD COLUMN AEROP_DATABERTURA DATE NOT NULL;

create table if not exists FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(50) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_TEL VARCHAR(20) NOT NULL,
FUNC_EMAIL VARCHAR(50) NOT NULL,
FUNC_CEP VARCHAR(10) NOT NULL,
FUNC_RUA VARCHAR(100) NOT NULL,
FUNC_RES_NUM INT,
FUNC_BAIRRO VARCHAR(50) NOT NULL,
FUNC_CIDADE VARCHAR(50) NOT NULL,
FUNC_UF VARCHAR(2),
FUNC_PAIS VARCHAR(30) NOT NULL,
FUNC_FUNCAO TEXT NOT NULL
);

ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_NOME VARCHAR(100) NOT NULL;

create table if not exists VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AERON VARCHAR(10) NOT NULL,
CONSTRAINT FK_VOO_AERONAVES FOREIGN KEY (VOO_AERON) REFERENCES AERONAVES(AERON_PREFIX)
);

ALTER TABLE VOOS ADD COLUMN VOO_DURACAO VARCHAR(20) NOT NULL;

create table if not exists RESERVAS(
RESERV_COD INT PRIMARY KEY,
RESERV_PASS VARCHAR(14) NOT NULL,
RESERV_VOO INT NOT NULL,
CONSTRAINT FK_RESERV_PASSAGEIROS FOREIGN KEY (RESERV_PASS) REFERENCES PASSAGEIROS(PASS_CPF),
CONSTRAINT FK_RESERV_VOOS FOREIGN KEY (RESERV_VOO) REFERENCES VOOS(VOO_ID)
);

ALTER TABLE RESERVAS ADD COLUMN RESERV_DESC TEXT;

create table if not exists VOOS_FUNCIONARIOS(
VF_VOO INT,
VF_FUNC INT,
PRIMARY KEY (VF_VOO,VF_FUNC),
CONSTRAINT FK_VF_VOOS FOREIGN KEY (VF_VOO) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_VF_FUNCIONARIOS FOREIGN KEY (VF_FUNC) REFERENCES FUNCIONARIOS(FUNC_ID)
);

ALTER TABLE VOOS_FUNCIONARIOS ADD COLUMN VF_DESC TEXT NOT NULL;

create table if not exists VOOS_AEROPORTOS(
VA_VOO INT,
VA_AEROP INT,
PRIMARY KEY (VA_VOO,VA_AEROP),
VA_STATUS ENUM('CHEGADA','SAIDA'),
CONSTRAINT FK_VA_VOOS FOREIGN KEY (VA_VOO) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_VA_AEROPORTOS FOREIGN KEY (VA_AEROP) REFERENCES AEROPORTOS(AEROP_COD)
);

ALTER TABLE VOOS_AEROPORTOS ADD COLUMN VA_DESC TEXT NOT NULL;

DROP DATABASE EST_CASO_II;
