#CRIANDO BANCO DE DADOS

create database EST_CASO_II;

use EST_CASO_II;

#CRIANDO TABELA PASSAGEIROS

create table if not exists PASSAGEIROS(
PASS_CPF VARCHAR(14) PRIMARY KEY,
PASS_NOME VARCHAR(50) NOT NULL,
PASS_DATANASC DATE NOT NULL,
PASS_TEL VARCHAR(20) NOT NULL,
PASS_EMAIL VARCHAR(50) NOT NULL,
PASS_CEP VARCHAR(10) NOT NULL,
PASS_RUA VARCHAR(100) NOT NULL,
PASS_RES_NUM INT,
PASS_BAIRRO VARCHAR(50) NOT NULL,
PASS_CIDADE VARCHAR(50) NOT NULL,
PASS_UF VARCHAR(2),
PASS_PAIS VARCHAR(30) NOT NULL
);

#DANDO COMANDOS DE ALTER NA TABELA PASSAGEIROS

ALTER TABLE PASSAGEIROS ADD COLUMN PASS_DESC TEXT NOT NULL;
ALTER TABLE PASSAGEIROS MODIFY COLUMN PASS_DESC VARCHAR(100);
ALTER TABLE PASSAGEIROS CHANGE COLUMN PASS_DESC PASS_DESCR VARCHAR(100);
ALTER TABLE PASSAGEIROS DROP COLUMN PASS_DESCR;

#CRIANDO TABELA AERONAVES

create table if not exists AERONAVES(
AERON_PREFIX VARCHAR(10) PRIMARY KEY,
AERON_MODEL VARCHAR(20) NOT NULL,
AERON_ANOFABR INT NOT NULL,
AERON_AUTON VARCHAR(10) NOT NULL,
AERON_CAPAC INT NOT NULL,
AERON_FABR VARCHAR(30) NOT NULL
);

#DANDO COMANDOS DE ALTER NA TABELA AERONAVES

ALTER TABLE AERONAVES ADD COLUMN AERON_DESC TEXT NOT NULL;
ALTER TABLE AERONAVES MODIFY COLUMN AERON_DESC VARCHAR(100);
ALTER TABLE AERONAVES CHANGE COLUMN AERON_DESC AERON_DESCR VARCHAR(100);
ALTER TABLE AERONAVES DROP COLUMN AERON_DESCR;

#CRIANDO TABELA AEROPORTOS

create table if not exists AEROPORTOS(
AEROP_COD INT PRIMARY KEY,
AEROP_NOME VARCHAR(50) NOT NULL,
AEROP_CIDADE VARCHAR(50) NOT NULL,
AEROP_PAIS VARCHAR(30) NOT NULL,
AEROP_LATITUDE DECIMAL(3,2) NOT NULL,
AEROP_LONGITUDE DECIMAL(3,2) NOT NULL
);

#DANDO COMANDOS DE ALTER NA TABELA AEROPORTOS

ALTER TABLE AEROPORTOS ADD COLUMN AEROP_DESC TEXT NOT NULL;
ALTER TABLE AEROPORTOS MODIFY COLUMN AEROP_DESC VARCHAR(100);
ALTER TABLE AEROPORTOS CHANGE COLUMN AEROP_DESC AEROP_DESCR VARCHAR(100);
ALTER TABLE AEROPORTOS DROP COLUMN AEROP_DESCR;

#CRIANDO TABELA FUNCIONARIOS

create table if not exists FUNCIONARIOS(
FUNC_ID INT PRIMARY KEY,
FUNC_NOME VARCHAR(50) NOT NULL,
FUNC_DATANASC DATE NOT NULL,
FUNC_TEL VARCHAR(20) NOT NULL,
FUNC_EMAIL VARCHAR(50) NOT NULL,
FUNC_CEP VARCHAR(10) NOT NULL,
FUNC_RUA VARCHAR(100) NOT NULL,
FUNC_RES_NUM INT,
FUNC_BAIRRO VARCHAR(50) NOT NULL,
FUNC_CIDADE VARCHAR(50) NOT NULL,
FUNC_UF VARCHAR(2),
FUNC_PAIS VARCHAR(30) NOT NULL,
FUNC_FUNCAO TEXT NOT NULL
);

#DANDO COMANDOS DE ALTER NA TABELA FUNCIONARIOS

ALTER TABLE FUNCIONARIOS ADD COLUMN FUNC_DESC TEXT NOT NULL;
ALTER TABLE FUNCIONARIOS MODIFY COLUMN FUNC_DESC VARCHAR(100);
ALTER TABLE FUNCIONARIOS CHANGE COLUMN FUNC_DESC FUNC_DESCR VARCHAR(100);
ALTER TABLE FUNCIONARIOS DROP COLUMN FUNC_DESCR;

#CRIANDO TABELA VOOS

create table if not exists VOOS(
VOO_ID INT PRIMARY KEY,
VOO_DATA DATE NOT NULL,
VOO_HORA TIME NOT NULL,
VOO_AERON VARCHAR(10) NOT NULL,
CONSTRAINT FK_VOO_AERONAVES FOREIGN KEY (VOO_AERON) REFERENCES AERONAVES(AERON_PREFIX)
);

#DANDO COMANDOS DE ALTER NA TABELA VOOS

ALTER TABLE VOOS ADD COLUMN VOO_DESC TEXT NOT NULL;
ALTER TABLE VOOS MODIFY COLUMN VOO_DESC VARCHAR(100);
ALTER TABLE VOOS CHANGE COLUMN VOO_DESC VOO_DESCR VARCHAR(100);
ALTER TABLE VOOS DROP COLUMN VOO_DESCR;

#CRIANDO TABELA RESERVAS

create table if not exists RESERVAS(
RESERV_COD INT PRIMARY KEY,
RESERV_PASS VARCHAR(14) NOT NULL,
RESERV_VOO INT NOT NULL,
CONSTRAINT FK_RESERV_PASSAGEIROS FOREIGN KEY (RESERV_PASS) REFERENCES PASSAGEIROS(PASS_CPF),
CONSTRAINT FK_RESERV_VOOS FOREIGN KEY (RESERV_VOO) REFERENCES VOOS(VOO_ID)
);

#DANDO COMANDOS DE ALTER NA TABELA RESERVAS

ALTER TABLE RESERVAS ADD COLUMN RESERV_DESC TEXT NOT NULL;
ALTER TABLE RESERVAS MODIFY COLUMN RESERV_DESC VARCHAR(100);
ALTER TABLE RESERVAS CHANGE COLUMN RESERV_DESC RESERV_DESCR VARCHAR(100);
ALTER TABLE RESERVAS DROP COLUMN RESERV_DESCR;

#CRIANDO TABELA VOOS_FUNCIONARIOS

create table if not exists VOOS_FUNCIONARIOS(
VF_VOO INT,
VF_FUNC INT,
PRIMARY KEY (VF_VOO,VF_FUNC),
CONSTRAINT FK_VF_VOOS FOREIGN KEY (VF_VOO) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_VF_FUNCIONARIOS FOREIGN KEY (VF_FUNC) REFERENCES FUNCIONARIOS(FUNC_ID)
);

#DANDO COMANDOS DE ALTER NA TABELA VOOS_FUNCIONARIOS

ALTER TABLE VOOS_FUNCIONARIOS ADD COLUMN VF_DESC TEXT NOT NULL;
ALTER TABLE VOOS_FUNCIONARIOS MODIFY COLUMN VF_DESC VARCHAR(100);
ALTER TABLE VOOS_FUNCIONARIOS CHANGE COLUMN VF_DESC VF_DESCR VARCHAR(100);
ALTER TABLE VOOS_FUNCIONARIOS DROP COLUMN VF_DESCR;

#CRIANDO TABELA VOOS_AEROPORTOS

create table if not exists VOOS_AEROPORTOS(
VA_VOO INT,
VA_AEROP INT,
PRIMARY KEY (VA_VOO,VA_AEROP),
VA_STATUS ENUM('CHEGADA','SAIDA'),
CONSTRAINT FK_VA_VOOS FOREIGN KEY (VA_VOO) REFERENCES VOOS(VOO_ID),
CONSTRAINT FK_VA_AEROPORTOS FOREIGN KEY (VA_AEROP) REFERENCES AEROPORTOS(AEROP_COD)
);

#DANDO COMANDOS DE ALTER NA TABELA VOOS_AEROPORTOS

ALTER TABLE VOOS_AEROPORTOS ADD COLUMN VA_DESC TEXT NOT NULL;
ALTER TABLE VOOS_AEROPORTOS MODIFY COLUMN VA_DESC VARCHAR(100);
ALTER TABLE VOOS_AEROPORTOS CHANGE COLUMN VA_DESC VA_DESCR VARCHAR(100);
ALTER TABLE VOOS_AEROPORTOS DROP COLUMN VA_DESCR;

#CRIAR TABELA AUXILIAR QUE RECEBERÁ UM COMANDO DE DROP

CREATE TABLE IF NOT EXISTS AUX(
AUX_ID INT PRIMARY KEY
)

ALTER TABLE AUX ADD COLUMN AUX_DESC TEXT;
ALTER TABLE AUX COLUMN AUX_DESC VARCHAR(100);
ALTER TABLE AUX CHANGE COLUMN AUX_DESC AUX_DESCR VARCHAR(100);
ALTER TABLE AUX DROP COLUMN AUX_DESCR;
  
DROP TABLE AUX;

