#CRIAR SCHEMA EST_CASO_4

create schema est_caso_04;

use est_caso_04;

#CRIAR TABELA INSTRUTORES

create table if not exists INSTRUTORES(
ID_INSTR INT PRIMARY KEY,
NOME_INSTR VARCHAR(50) NOT NULL,
CPF_INSTR VARCHAR(14) NOT NULL,
DATA_NASC_INSTR DATE NOT NULL,
CEP_INSTR VARCHAR(10) NOT NULL,
RUA_INSTR VARCHAR(100) NOT NULL,
NUM_RES_INSTR INT,
BAIRRO_INSTR VARCHAR(50) NOT NULL,
CIDADE_INSTR VARCHAR(50) NOT NULL,
UF_INSTR VARCHAR(2) NOT NULL
);

#DAR COMANDOS DE ALTER NA TABELA INSTRUTORES

ALTER TABLE INSTRUTORES ADD COLUMN EMAIL_INSTR VARCHAR(100) NOT NULL;
ALTER TABLE INSTRUTORES ADD COLUMN TEL_INSTR VARCHAR(20);
ALTER TABLE INSTRUTORES MODIFY COLUMN EMAIL_INSTR VARCHAR(150);
ALTER TABLE INSTRUTORES CHANGE COLUMN TEL_INSTR TELE_INSTR VARCHAR(20);
ALTER TABLE INSTRUTORES DROP COLUMN TELE_INSTR;

#CRIAR TABELA MODALIDADES

create table if not exists MODALIDADES(
ID_MODAL INT PRIMARY KEY,
NOME_MODAL VARCHAR(50) NOT NULL
);

#DAR COMANDOS DE ALTER NA TABELA MODALIDADES

ALTER TABLE MODALIDADES ADD COLUMN DESC_MODAL TEXT NOT NULL;
ALTER TABLE MODALIDADES MODIFY COLUMN DESC_MODAL VARCHAR(100);
ALTER TABLE MODALIDADES CHANGE COLUMN DESC_MODAL DESCR_MODAL VARCHAR(100);
ALTER TABLE MODALIDADES DROP COLUMN DESCR_MODAL;

#CRIAR TABELA ALUNOS

create table if not exists ALUNOS(
ID_ALUNO INT PRIMARY KEY,
NOME_ALUNO VARCHAR(50) NOT NULL,
CPF_ALUNO VARCHAR(14) NOT NULL,
DATA_NASC_ALUNO DATE NOT NULL,
CEP_ALUNO VARCHAR(10) NOT NULL,
RUA_ALUNO VARCHAR(100) NOT NULL,
NUM_RES_ALUNO INT,
BAIRRO_ALUNO VARCHAR(50) NOT NULL,
CIDADE_ALUNO VARCHAR(50) NOT NULL,
UF_ALUNO VARCHAR(2) NOT NULL
);

#DAR COMANDOS DE ALTER NA TABELA ALUNOS

ALTER TABLE ALUNOS ADD COLUMN EMAIL_ALUNO VARCHAR(100) NOT NULL;
ALTER TABLE ALUNOS ADD COLUMN TEL_ALUNO VARCHAR(20);
ALTER TABLE ALUNOS MODIFY COLUMN EMAIL_ALUNO VARCHAR(150);
ALTER TABLE ALUNOS CHANGE COLUMN TEL_ALUNO TELE_ALUNO VARCHAR(20);
ALTER TABLE ALUNOS DROP COLUMN TELE_ALUNO;

#CRIAR TABELA AULAS

create table if not exists AULAS(
ID_AULA INT PRIMARY KEY,
HORA_AULA TIME NOT NULL,
DIA_AULA ENUM ('SEGUNDA','TERCA','QUARTA','QUINTA','SEXTA','SABADO','DOMINGO'),
CAPAC_AULA INT NOT NULL,
INSTR_AULA INT NOT NULL,
MODAL_AULA INT NOT NULL,
CONSTRAINT FK_AULA_INSTRUTORES FOREIGN KEY (INSTR_AULA) REFERENCES INSTRUTORES(ID_INSTR),
CONSTRAINT FK_MODALIDADES FOREIGN KEY (MODAL_AULA) references MODALIDADES(ID_MODAL)
);

#DAR COMANDOS DE ALTER NA TABELA AULAS

ALTER TABLE AULAS ADD COLUMN DESC_AULA TEXT NOT NULL;
ALTER TABLE AULAS MODIFY COLUMN DESC_AULA VARCHAR(100);
ALTER TABLE AULAS CHANGE COLUMN DESC_AULA DESCR_AULA VARCHAR(100);
ALTER TABLE AULAS DROP COLUMN DESCR_AULA;

#CRIAR TABELA PLANOS_TREINAMENTO

create table if not exists  PLANOS_TREINAMENTO(
ID_PLAN INT PRIMARY KEY,
STATUS_PLAN TEXT NOT NULL,
INSTR_PLAN INT NOT NULL,
ALUNO_PLAN INT NOT NULL,
CONSTRAINT FK_PLAN_INSTRUTORES FOREIGN KEY (INSTR_PLAN) REFERENCES INSTRUTORES(ID_INSTR),
CONSTRAINT FK_PLAN_ALUNOS FOREIGN KEY (ALUNO_PLAN) REFERENCES ALUNOS(ID_ALUNO)
);

#DAR COMANDOS DE ALTER NA TABELA PLANOS_TREINAMENTO

ALTER TABLE PLANOS_TREINAMENTO ADD COLUMN DESC_PLAN TEXT NOT NULL;
ALTER TABLE PLANOS_TREINAMENTO MODIFY COLUMN DESC_PLAN VARCHAR(100);
ALTER TABLE PLANOS_TREINAMENTO CHANGE COLUMN DESC_PLAN DESCR_PLAN VARCHAR(100);
ALTER TABLE PLANOS_TREINAMENTO DROP COLUMN DESCR_PLAN;

#CRIAR TABELA PAGAMENTOS

create table if not exists PAGAMENTOS(
ID_PAG INT PRIMARY KEY,
DATA_PAG DATE NOT NULL,
STATUS_PAG ENUM('PAGO','PENDENTE') NOT NULL,
VALOR_PAG DECIMAL(4,2) NOT NULL,
ALUNO_PAG INT NOT NULL,
CONSTRAINT FK_PAG_ALUNOS FOREIGN KEY (ALUNO_PAG) REFERENCES ALUNOS(ID_ALUNO)
);

#DAR COMANDOS DE ALTER NA TABELA PAGAMENTOS

ALTER TABLE PAGAMENTOS ADD COLUMN DESC_PAG TEXT NOT NULL;
ALTER TABLE PAGAMENTOS MODIFY COLUMN DESC_PAG VARCHAR(100);
ALTER TABLE PAGAMENTOS CHANGE COLUMN DESC_PAG DESCR_PAG VARCHAR(100);
ALTER TABLE PAGAMENTOS DROP COLUMN DESCR_PAG;

#CRIAR TABELA ALUNOS_AULAS

create table if not exists ALUNOS_AULAS(
ALAU_AULA INT,
ALAU_ALUNO INT,
PRIMARY KEY (ALAU_AULA, ALAU_ALUNO),
CONSTRAINT FK_ALAU_AULAS FOREIGN KEY (ALAU_AULA) REFERENCES AULAS(ID_AULA),
CONSTRAINT FK_ALAU_ALUNOS FOREIGN KEY (ALAU_ALUNO) REFERENCES ALUNOS(ID_ALUNO)
);

#DAR COMANDOS DE ALTER NA TABELA ALUNOS_AULAS

ALTER TABLE ALUNOS_AULAS ADD COLUMN DESC_ALAU TEXT;
ALTER TABLE ALUNOS_AULAS MODIFY COLUMN DESC_ALAU VARCHAR(100);
ALTER TABLE ALUNOS_AULAS CHANGE COLUMN DESC_ALAU DESCR_ALAU VARCHAR(100);
ALTER TABLE ALUNOS_AULAS DROP COLUMN DESCR_ALAU;

#DAR COMANDO DE DROP SCHEMA

DROP SCHEMA est_caso_04; 
