create schema ec3;

use ec3;

create table if not exists CLIENTES(
COD_CLIENT INT PRIMARY KEY,
CNPJ_CLIENT VARCHAR(20) NOT NULL,
RAZ_SOC_CLIENT VARCHAR(50) NOT NULL,
RAM_ATV_CLIENT VARCHAR(100) NOT NULL,
DATA_CAD_CLIENT DATE NOT NULL
);

create table if not exists FORNECEDORES(
COD_FORN INT PRIMARY KEY,
CNPJ_FORN VARCHAR(20) NOT NULL,
RAZ_SOC_FORN VARCHAR(50) NOT NULL
);

create table if not exists TIPOS_ENDERECOS(
COD_TIPO_END INT PRIMARY KEY,
NOME_TIPO_END VARCHAR(20) NOT NULL
);

create table if not exists QUALIFICACOES(
COD_QLF INT PRIMARY KEY,
NOME_QLF VARCHAR(20) NOT NULL
);

create table if not exists PESSOAS_CONTATO(
COD_PES_CONT INT PRIMARY KEY,
NOME_PES_CONT VARCHAR(50) NOT NULL,
CPF_PES_CONT VARCHAR(14) NOT NULL
);

create table if not exists CARGOS(
COD_CARGO INT PRIMARY KEY,
NOME_CARGO VARCHAR(20) NOT NULL,
DESC_FUNC_CARGO TEXT NOT NULL
);

create table if not exists PRODUTOS(
COD_PROD INT PRIMARY KEY,
NOME_PROD VARCHAR(30) NOT NULL,
COR_PROD VARCHAR(15) NOT NULL,
DIM_PROD TEXT NOT NULL,
PESO_PROD DECIMAL(10,3) NOT NULL,
PRECO_PROD DECIMAL(10,2) NOT NULL,
TEMP_FAB_PROD VARCHAR(10) NOT NULL,
DESENHO_PROD BLOB NOT NULL,
HRS_MOBRA_PROD VARCHAR(10) NOT NULL
);

create table if not exists TIPOS_COMPONENTES(
COD_TIP_COMP INT PRIMARY KEY,
NOME_TIP_COMP VARCHAR(20) NOT NULL
);

create table if not exists MAQUINAS(
COD_MAQ INT PRIMARY KEY,
TEMP_VID_MAQ VARCHAR(20) NOT NULL,
DATA_CMP_MAQ DATE NOT NULL,
DATA_FIM_GART_MAQ DATE NOT NULL
);

create table if not exists EMPREGADOS(
MATR_EMPREG INT PRIMARY KEY,
NOME_EMPREG VARCHAR(100) NOT NULL,
CPF_EMPREG VARCHAR(14) NOT NULL,
SAL_EMPREG DECIMAL(10,2) NOT NULL,
DATA_ADM_EMPREG DATE NOT NULL,
CARGO_EMPREG INT NOT NULL,
CONSTRAINT FK_CARGOS FOREIGN KEY (CARGO_EMPREG) REFERENCES CARGOS(COD_CARGO)
);

create table if not exists ENDERECOS(
COD_ENDRC INT PRIMARY KEY,
CEP_ENDRC VARCHAR(10) NOT NULL,
RUA_ENDRC VARCHAR(100) NOT NULL,
NUM_ENDRC INT,
COMP_ENDRC VARCHAR(100) NOT NULL,
LOG_ENDRC VARCHAR(100) NOT NULL,
BAIRRO_ENDRC VARCHAR(100) NOT NULL,
CID_ENDRC VARCHAR(100) NOT NULL,
ESTADO_ENDRC VARCHAR(100) NOT NULL,
TIPO_END_ENDRC INT NOT NULL,
FORN_ENDRC INT NOT NULL,
CLIENT_ENDRC INT NOT NULL,
EMPREG_ENDRC INT NOT NULL,
CONSTRAINT FK_TIPOS_ENDERECOS FOREIGN KEY (TIPO_END_ENDRC) REFERENCES TIPOS_ENDERECOS(COD_TIPO_END),
CONSTRAINT FK_FORNECEDORES FOREIGN KEY (FORN_ENDRC) REFERENCES FORNECEDORES(COD_FORN),
CONSTRAINT FK_CLIENTES FOREIGN KEY (CLIENT_ENDRC) REFERENCES CLIENTES(COD_CLIENT),
CONSTRAINT FK_EMPREGADOS FOREIGN KEY (EMPREG_ENDRC) REFERENCES EMPREGADOS(MATR_EMPREG)
);

create table if not exists TELEFONES(
DDD_TEL VARCHAR(3),
NUM_TEL VARCHAR(15),
PRIMARY KEY (DDD_TEL, NUM_TEL),
FORN_TEL INT NOT NULL,
CLIENT_TEL INT NOT NULL,
EMPREG_TEL INT NOT NULL,
PES_CONT_TEL INT NOT NULL,
CONSTRAINT FK_FORNECEDORES1 FOREIGN KEY (FORN_TEL) REFERENCES FORNECEDORES(COD_FORN),
CONSTRAINT FK_CLIENTES1 FOREIGN KEY (CLIENT_TEL) REFERENCES CLIENTES(COD_CLIENT),
CONSTRAINT FK_EMPREGADOS1 FOREIGN KEY (EMPREG_TEL) REFERENCES EMPREGADOS(MATR_EMPREG),
CONSTRAINT FK_PESSOAS_CONTATO FOREIGN KEY (PES_CONT_TEL) REFERENCES PESSOAS_CONTATO(COD_PES_CONT)
);

create table if not exists ENCOMENDAS(
COD_ENCOM INT PRIMARY KEY,
DATA_INCL_ENCOM DATE NOT NULL,
VALOR_TOTAL_ENCOM DECIMAL(10,2) NOT NULL,
VALOR_DESC_ENCOM DECIMAL(10,2) NOT NULL,
QTD_PARC_ENCOM INT NOT NULL,
ID_FORM_PAG_ENCOM INT NOT NULL,
CLIENT_ENCOM INT NOT NULL,
CONSTRAINT FK_CLIENTES2 FOREIGN KEY (CLIENT_ENCOM) REFERENCES CLIENTES(COD_CLIENT)
);

create table if not exists COMPONENTES(
COD_COMP INT PRIMARY KEY,
NOME_COMP VARCHAR(100) NOT NULL,
QTD_EST_COMP INT NOT NULL,
PRC_UNIT_COMP DECIMAL(10,2) NOT NULL,
UNIDADE_COMP VARCHAR(50) NOT NULL,
TIP_COMP_COMP INT NOT NULL,
CONSTRAINT FK_TIPOS_COMPONENTES FOREIGN KEY (TIP_COMP_COMP) REFERENCES TIPOS_COMPONENTES(COD_TIP_COMP)
);

create table if not exists REGISTROS_MANUTENCAO(
COD_RM INT PRIMARY KEY,
DATA_RM DATE NOT NULL,
DESC_RM TEXT NOT NULL,
MAQ_RM INT NOT NULL,
CONSTRAINT FK_MAQUINAS FOREIGN KEY (MAQ_RM) REFERENCES MAQUINAS(COD_MAQ)
);

create table if not exists REGISTROS_ESPECIFICOS(
COD_RE INT PRIMARY KEY,
QTD_NEC_RE INT NOT NULL,
UNID_RE VARCHAR(50) NOT NULL,
TEMP_USO_RE VARCHAR(10) NOT NULL,
HRS_MOBRA_RE VARCHAR(10) NOT NULL,
MAQ_RE INT NOT NULL,
COMP_RE INT NOT NULL,
EMPREG_RE INT NOT NULL,
PROD_RE INT NOT NULL,
CONSTRAINT FK_MAQUINAS2 foreign key (MAQ_RE) REFERENCES MAQUINAS(COD_MAQ),
CONSTRAINT FK_COMPONENTES FOREIGN KEY (COMP_RE) REFERENCES COMPONENTES(COD_COMP),
CONSTRAINT FK_EMPREGADOS3 foreign key (EMPREG_RE) references EMPREGADOS(MATR_EMPREG),
CONSTRAINT FK_PRODUTOS FOREIGN KEY (PROD_RE) REFERENCES PRODUTOS(COD_PROD)
);

create table if not exists REGISTROS_SUPRIMENTO(
RGSP_PROD INT,
RGSP_COMP INT,
PRIMARY KEY(RGSP_PROD, RGSP_COMP),
RGSP_QTD INT NOT NULL,
RGSP_DATA_NEC DATE NOT NULL,
CONSTRAINT FK_PRODUTOS2 FOREIGN KEY (RGSP_PROD) REFERENCES PRODUTOS(COD_PROD),
CONSTRAINT FK_COMPONENTES2 FOREIGN KEY (RGSP_COMP) REFERENCES COMPONENTES(COD_COMP)
);

create table if not exists PRODUTOS_ENCOMENDAS(
PREN_PROD INT,
PREN_ENCOM INT,
PRIMARY KEY(PREN_PROD, PREN_ENCOM),
CONSTRAINT FK_PRODUTOS3 FOREIGN KEY (PREN_PROD) REFERENCES PRODUTOS(COD_PROD),
CONSTRAINT FK_ENCOMENDAS FOREIGN KEY (PREN_ENCOM) REFERENCES ENCOMENDAS(COD_ENCOM)
);

create table if not exists EMPREGADOS_QUALIFICACOES(
EMQL_EMPREG INT,
EMQL_QLF INT,
PRIMARY KEY(EMQL_EMPREG, EMQL_QLF),
CONSTRAINT FK_EMPREGADOS4 FOREIGN KEY (EMQL_EMPREG) REFERENCES EMPREGADOS(MATR_EMPREG),
CONSTRAINT FK_QUALIFICACOES FOREIGN KEY (EMQL_QLF) REFERENCES QUALIFICACOES(COD_QLF)
);

create table if not exists COMPONENTES_FORNECEDORES(
CMFR_COMP INT,
CMFR_FORN INT,
PRIMARY KEY(CMFR_COMP, CMFR_FORN),
CONSTRAINT FK_COMPONENTES3 FOREIGN KEY (CMFR_COMP) REFERENCES COMPONENTES(COD_COMP),
CONSTRAINT FK_FORNECEDORES2 FOREIGN KEY (CMFR_FORN) REFERENCES FORNECEDORES(COD_FORN)
);

ALTER TABLE CLIENTES MODIFY COLUMN RAZ_SOC_CLIENT VARCHAR(100);

ALTER TABLE FORNECEDORES MODIFY COLUMN RAZ_SOC_FORN VARCHAR(100);

ALTER TABLE tipos_enderecos MODIFY COLUMN NOME_TIPO_END VARCHAR(30);

ALTER TABLE qualificacoes MODIFY COLUMN NOME_QLF VARCHAR(30);

ALTER TABLE pessoas_contato MODIFY COLUMN NOME_PES_CONT VARCHAR(100);

ALTER TABLE CARGOS MODIFY COLUMN NOME_CARGO VARCHAR(30);

ALTER TABLE PRODUTOS MODIFY COLUMN PRECO_PROD DECIMAL(12,2);

ALTER TABLE tipos_componentes MODIFY COLUMN NOME_TIP_COMP VARCHAR(30);

ALTER TABLE MAQUINAS MODIFY COLUMN TEMP_VID_MAQ VARCHAR(30);

ALTER TABLE empregados MODIFY COLUMN SAL_EMPREG DECIMAL(6,2);

ALTER TABLE enderecos CHANGE COLUMN NUM_ENDRC NUM_LOC_ENDRC INT;

ALTER TABLE TELEFONES MODIFY COLUMN DDD_TEL VARCHAR(4);

ALTER TABLE encomendas CHANGE COLUMN QTD_PARC_ENCOM QTD_PRC_ENCOM INT;

ALTER TABLE COMPONENTES MODIFY COLUMN UNIDADE_COMP VARCHAR(100);

ALTER TABLE registros_manutencao CHANGE COLUMN COD_RM CODG_RM INT;

ALTER TABLE registros_especificos MODIFY COLUMN TEMP_USO_RE VARCHAR(20);

ALTER TABLE registros_suprimento CHANGE COLUMN RGSP_QTD RGSP_QTDS INT;

ALTER TABLE produtos_encomendas ADD COLUMN PREN_DESC TEXT;

ALTER TABLE empregados_qualificacoes ADD COLUMN EMQL_DESC TEXT;

ALTER TABLE componentes_fornecedores ADD COLUMN CMFR_DESC TEXT;

DROP SCHEMA ec3; 
