create schema est_caso_04;

use est_caso_04;

create table if not exists INSTRUTORES(
ID_INSTR INT PRIMARY KEY,
NOME_INSTR VARCHAR(50) NOT NULL,
CPF_INSTR VARCHAR(14) NOT NULL,
DATA_NASC_INSTR DATE NOT NULL,
CEP_INSTR VARCHAR(10) NOT NULL,
RUA_INSTR VARCHAR(100) NOT NULL,
NUM_RES_INSTR INT,
BAIRRO_INSTR VARCHAR(50) NOT NULL,
CIDADE_INSTR VARCHAR(50) NOT NULL,
UF_INSTR VARCHAR(2) NOT NULL
);

ALTER TABLE INSTRUTORES ADD COLUMN EMAIL_INSTR VARCHAR(100) NOT NULL;
ALTER TABLE INSTRUTORES ADD COLUMN TEL_INSTR VARCHAR(20);

create table if not exists MODALIDADES(
ID_MODAL INT PRIMARY KEY,
NOME_MODAL VARCHAR(50) NOT NULL
);

ALTER TABLE MODALIDADES ADD COLUMN DESC_MODAL TEXT NOT NULL;

create table if not exists ALUNOS(
ID_ALUNO INT PRIMARY KEY,
NOME_ALUNO VARCHAR(50) NOT NULL,
CPF_ALUNO VARCHAR(14) NOT NULL,
DATA_NASC_ALUNO DATE NOT NULL,
CEP_ALUNO VARCHAR(10) NOT NULL,
RUA_ALUNO VARCHAR(100) NOT NULL,
NUM_RES_ALUNO INT,
BAIRRO_ALUNO VARCHAR(50) NOT NULL,
CIDADE_ALUNO VARCHAR(50) NOT NULL,
UF_ALUNO VARCHAR(2) NOT NULL
);

ALTER TABLE ALUNOS ADD COLUMN EMAIL_ALUNO VARCHAR(100) NOT NULL;
ALTER TABLE ALUNOS ADD COLUMN TEL_ALUNO VARCHAR(20);

create table if not exists AULAS(
ID_AULA INT PRIMARY KEY,
HORA_AULA TIME NOT NULL,
DIA_AULA ENUM ('SEGUNDA','TERCA','QUARTA','QUINTA','SEXTA','SABADO','DOMINGO'),
CAPAC_AULA INT NOT NULL,
INSTR_AULA INT NOT NULL,
MODAL_AULA INT NOT NULL,
CONSTRAINT FK_AULA_INSTRUTORES FOREIGN KEY (INSTR_AULA) REFERENCES INSTRUTORES(ID_INSTR),
CONSTRAINT FK_MODALIDADES FOREIGN KEY (MODAL_AULA) references MODALIDADES(ID_MODAL)
);

ALTER TABLE AULAS ADD COLUMN DESC_AULA TEXT NOT NULL;

create table if not exists  PLANOS_TREINAMENTO(
ID_PLAN INT PRIMARY KEY,
STATUS_PLAN TEXT NOT NULL,
INSTR_PLAN INT NOT NULL,
ALUNO_PLAN INT NOT NULL,
CONSTRAINT FK_PLAN_INSTRUTORES FOREIGN KEY (INSTR_PLAN) REFERENCES INSTRUTORES(ID_INSTR),
CONSTRAINT FK_PLAN_ALUNOS FOREIGN KEY (ALUNO_PLAN) REFERENCES ALUNOS(ID_ALUNO)
);

ALTER TABLE PLANOS_TREINAMENTO ADD COLUMN DESC_PLAN TEXT NOT NULL;

create table if not exists PAGAMENTOS(
ID_PAG INT PRIMARY KEY,
DATA_PAG DATE NOT NULL,
STATUS_PAG ENUM('PAGO','PENDENTE') NOT NULL,
VALOR_PAG DECIMAL(4,2) NOT NULL,
ALUNO_PAG INT NOT NULL,
CONSTRAINT FK_PAG_ALUNOS FOREIGN KEY (ALUNO_PAG) REFERENCES ALUNOS(ID_ALUNO)
);

ALTER TABLE PAGAMENTOS MODIFY COLUMN VALOR_PAG DECIMAL(3,2) NOT NULL;

create table if not exists ALUNOS_AULAS(
ALAU_AULA INT,
ALAU_ALUNO INT,
PRIMARY KEY (ALAU_AULA, ALAU_ALUNO),
CONSTRAINT FK_ALAU_AULAS FOREIGN KEY (ALAU_AULA) REFERENCES AULAS(ID_AULA),
CONSTRAINT FK_ALAU_ALUNOS FOREIGN KEY (ALAU_ALUNO) REFERENCES ALUNOS(ID_ALUNO)
);

ALTER TABLE ALUNOS_AULAS ADD COLUMN DESC_ALAU TEXT;
ALTER TABLE ALUNOS_AULAS DROP COLUMN DESC_ALAU;

DROP SCHEMA est_caso_04; 